[package]
name = "libplacebo-sys"
version = "0.0.0"
edition = "2021"

[build-dependencies]
bindgen = "0.69.4"
dunce = "1.0.4"

[package.metadata.system-deps]
libplacebo = "*"

[features]
default = ["vendored"]
vendored = []
